name: "new monolithic pipeline"
on: 
  workflow_dispatch:

jobs:
  terraform-init-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: ci-nodejs-package
      uses: grandmasterdev/github-action-ci-nodejs-package@v16.0.2
      
      
