name: "NewMonolithic Pipeline"
on: 
  workflow_dispatch:

jobs:
  buildstage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Install NodeJS Dependencies
      uses: luisfuentech/gha-cache-deps@v1.2.3
      with: 
        node-manager: npm
        lock-file: package-lock.json
    - name: Build React App (ignore ESLint warnings)
      run: npm run build
      env:
        CI: false
    - name: Set Artifact Name
      id: set-artifact-name
      run: echo "name=react-build" >> $GITHUB_OUTPUT

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
         name: react-build
         path: build/ 

  deploystage:
    needs: buildstage
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: react-build
          path: build/

      - name: Upload build folder to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          source: "build/*"
          target: "/home/${{ secrets.VM_USERNAME }}/react-app"

      - name: Install & Configure NGINX on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl enable nginx
            sudo systemctl start nginx

            sudo mkdir -p /var/www/react-app
            sudo cp -r /home/${{ secrets.VM_USERNAME }}/react-app/* /var/www/react-app/

            sudo bash -c 'cat > /etc/nginx/sites-available/react-app <<EOF
            server {
                listen 80;
                server_name _;
                root /var/www/react-app;
                index index.html;
                location / {
                    try_files \$uri /index.html;
                }
            }
EOF'

            sudo ln -sf /etc/nginx/sites-available/react-app /etc/nginx/sites-enabled/react-app
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo nginx -t
            sudo systemctl restart nginx
   
          

      
    
    
      
      
